// Code generated by "stringer -type token -linecomment"; DO NOT EDIT.

package syntax

import "strconv"

const _token_name = "EOFnameliteralopop=opop=:=<-*->([{)]},;:....breakcasechanconstcontinuedefaultdeferelsefallthroughforfuncgogotoifimportinterfacemappackagerangereturnselectstructswitchtypevar"

var _token_index = [...]uint8{0, 3, 7, 14, 16, 19, 23, 24, 26, 28, 29, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 44, 49, 53, 57, 62, 70, 77, 82, 86, 97, 100, 104, 106, 110, 112, 118, 127, 130, 137, 142, 148, 154, 160, 166, 170, 173, 173}

func (i token) String() string {
	i -= 1
	if i >= token(len(_token_index)-1) {
		return "token(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _token_name[_token_index[i]:_token_index[i+1]]
}
